#######
# Compiled from pt.evs/functions/mcscript/load.mcscript
# to .//pt.evs/data/pt.evs/functions/mcscript/load.mcfunction
#
# Generated by Minecraft Script for 1.16
######
# Juanoreboard objectives add patio.demo dummy
scoreboard objectives add pato.demo dummy
scoreboard objectives add pato.ticks dummy
scoreboard objectives add pato.seconds dummy
scoreboard objectives add pato.raidEv1Memb dummy
scoreboard objectives add pato.rdEv1KillC dummy
scoreboard objectives add pato.raidLevel dummy
scoreboard objectives add pato.RaidID dummy
scoreboard objectives add pato.currntEvent dummy
scoreboard objectives add pato.Craft dummy
scoreboard objectives add pato.joins dummy
scoreboard objectives add pato.Data dummy
scoreboard objectives add yBlaze.tickSummon dummy
scoreboard objectives add register trigger
scoreboard objectives add login trigger
scoreboard objectives add pato.password dummy
scoreboard objectives add pato.subtraction dummy
scoreboard objectives add pato.equals dummy
scoreboard objectives add dRav.tickSuper dummy
scoreboard objectives add changepass trigger
