#######
# Compiled from data/pt.evs/functions/misc.mcscript
# to .//pt.evs/data/pt.evs/functions/counter_trigger.mcfunction
#
# Generated by Minecraft Script for 1.16
######
tellraw @s {"text": "[ACTIVAR CONTADOR]","color": "red","clickEvent": {"action": "run_command","value": "/function pt.evs:events/counter/counter_activate"}}
