#######
# Compiled from data/pt.evs/functions/framework.mcscript
# to .//pt.evs/data/pt.evs/functions/framework.mcfunction
#
# Generated by Minecraft Script for 1.16
######
scoreboard objectives add pato.health health
scoreboard objectives modify pato.health displayname {"text": "de vida","color": "gold"}
scoreboard objectives setdisplay belowName pato.health
scoreboard objectives setdisplay list pato.health









scoreboard objectives add pato.KillCount playerKillCount {"text": "Contador de Kills","color": "red","bold": true}

scoreboard objectives add pato.rdEv1KillC dummy {"text": "Raid 1 Kill Counter","color": "red","bold": true}

scoreboard objectives add pato.joinFuncFix custom:leave_game

scoreboard objectives add pato.jump custom:jump




















