#######
# Compiled from data/pt.evs/functions/load.mcscript
# to .//pt.evs/data/pt.evs/functions/load.mcfunction
#
# Generated by Minecraft Script for 1.16
######
function pt.evs:mcscript/load

# Carga
function pt.evs:framework
# Bossbars
# Por ahora, NO
# Gamerules
gamerule playersSleepingPercentage 1
gamerule commandBlockOutput false
# MODO DEMO
scoreboard players set .Demo pato.demo 1
scoreboard players set @a pato.demo 1
# Eventos
#por el evento de este domingo, estará desactivado por poco tiempo (solo es eso)
#scoreboard players set .Event pato.currntEvent 1
scoreboard players set .Event pato.currntEvent 2