#######
# Compiled from data/pt.evs/functions/main.mcscript
# to .//pt.evs/data/pt.evs/functions/main.mcfunction
#
# Generated by Minecraft Script for 1.16
######
# Contar segundos NO DEMO
execute unless score .Demo pato.demo matches 1 run scoreboard players add @a pato.ticks 1

execute unless score .Demo pato.demo matches 1 as @a[scores={pato.ticks=20..}] run scoreboard players add @s pato.seconds 1
execute unless score .Demo pato.demo matches 1 as @a[scores={pato.ticks=20..}] run scoreboard players reset @s pato.seconds

# Player Join Function Fixer
execute as @a run function pt.evs:join_function_fixer
# Resetear Saltos
scoreboard players reset @a pato.jump
function pt.evs:login/trigger_enable
execute as @a[tag=pato.onLoginResponse,limit=1] at @s run effect give @s slow_falling 15 0 true
execute as @a[tag=pato.onLoginResponse,limit=1] at @s run tp @s @e[type=armor_stand,tag=pato.previousLocation,distance=..16,limit=1]
execute as @a[tag=pato.onLoginResponse,limit=1] at @s run title @s actionbar [{"text": "Jugando como "},{"selector": "@s","color": "yellow","bold": true}]
execute as @e[type=armor_stand,tag=pato.previousLocation] at @s run tp @a[tag=pato.onLoginResponse,distance=..16] ~ ~16 ~