#######
# Compiled from data/pt.evs/functions/event_counter.mcscript
# to .//pt.evs/data/pt.evs/functions/events/counter/counter_27.mcfunction
#
# Generated by Minecraft Script for 1.16
######
title @a actionbar {"text": "PatoEvento en 27 segundos...","color": "green"}

# Extended from data/pt.evs/functions/event_counter.mcscript
# to .//pt.evs/data/pt.evs/functions/events/counter/counter_27.mcfunction
schedule function pt.evs:events/counter/counter_26 1s
