#######
# Compiled from data/pt.evs/functions/event_counter.mcscript
# to .//pt.evs/data/pt.evs/functions/events/counter/counter_5.mcfunction
#
# Generated by Minecraft Script for 1.16
######
title @a actionbar {"text": "PatoEvento en 5 segundos...","color": "green"}

# Extended from data/pt.evs/functions/event_counter.mcscript
# to .//pt.evs/data/pt.evs/functions/events/counter/counter_5.mcfunction
title @a title {"text": "PatoEvento en","color": "gold","bold": true}
title @a subtitle {"text": "5","color": "green"}
tellraw @a {"text": "PatoEvento en 5 segundos...","color": "green"}
schedule function pt.evs:events/counter/counter_4 1s
