#######
# Compiled from data/pt.evs/functions/event_counter.mcscript
# to .//pt.evs/data/pt.evs/functions/events/counter/counter_go.mcfunction
#
# Generated by Minecraft Script for 1.16
######
title @a title {"text": "Let's Go!","color": "green","bold": true,"italic": true}
tellraw @a {"text": "LET'S GO!!!","color": "red","bold": true,"italic": true}
tp @a @e[type=armor_stand,tag=pato.point,limit=1]
kill @e[type=armor_stand,tag=pato.point]
function pt.evs:events/counter/schedule_events
