#######
# Compiled from data/pt.evs/functions/event_counter.mcscript
# to .//pt.evs/data/pt.evs/functions/events/counter/schedule_events.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @r at @s if score .Event pato.currntEvent matches 2 run schedule function pt.evs:events/minigames/hunger_games/trigger 3s
