#######
# Compiled from data/pt.evs/functions/login_system.mcscript
# to .//pt.evs/data/pt.evs/functions/login/changepass.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @a if entity @s[tag=pato.registered, tag=!pato.onLoginResponse] unless score @s changepass matches 0 store result score @s pato.password run scoreboard players operation @s pato.password = @s changepass
execute as @a if entity @s[tag=pato.registered, tag=!pato.onLoginResponse] unless score @s changepass matches 0 run tellraw @s [{"text": "[SISTEMA DE CUENTAS] ","color": "green"},{"text": "Contraseña actualizada con éxito. Tu nueva contraseña es ","color": "yellow"},{"score":{"name": "@s","objective": "pato.password"},"color": "gold"}]
execute as @a if entity @s[tag=pato.registered, tag=!pato.onLoginResponse] unless score @s changepass matches 0 run scoreboard players reset @s changepass
