#######
# Compiled from data/pt.evs/functions/login_system.mcscript
# to .//pt.evs/data/pt.evs/functions/login/checker_message.mcfunction
#
# Generated by Minecraft Script for 1.16
######
effect give @s mining_fatigue infinite 50 true
effect give @s levitation infinite 255 true
effect give @s slowness infinite 7 true
effect give @s blindness infinite 0 true
effect give @s resistance infinite 200 true
effect give @s fire_resistance infinite 0 true
effect give @s weakness infinite 200 true
effect give @s invisibility infinite 0 true
execute as @s at @s if entity @s[tag=pato.registered] run tellraw @s [{"text": "[SISTEMA DE CUENTAS] ","color": "green"},{"text": "Por favor inicie sesión con ","color": "yellow"},{"text": "/trigger login set <contraseña>","color": "gold"}]
execute as @s at @s if entity @s[tag=pato.registered] run tellraw @s [{"text": "[SISTEMA DE CUENTAS] ","color": "green"},{"text": "Si se le olvidó su contraseña, contáctese con el owner de PatoLand","color": "red"}]
execute as @s at @s unless entity @s[tag=pato.registered] run tellraw @s [{"text": "[SISTEMA DE CUENTAS] ","color": "green"},{"text": "Por favor regístrese con ","color": "yellow"},{"text": "/trigger register set <contraseña>","color": "gold"}]
execute as @s at @s unless entity @s[tag=pato.registered] run tellraw @s [{"text": "[SISTEMA DE CUENTAS] ","color": "green"},{"text": "La contraseña sólo puede contener NÚMEROS","color": "red"}]
execute as @s at @s unless entity @s[tag=pato.registered] run tellraw @s [{"text": "[SISTEMA DE CUENTAS] ","color": "green"},{"text": "Luego de registrarse, es importante ejecutar /trigger login set <contraseña> para poder iniciar sesión","color": "gold"}]
execute as @s at @s unless entity @s[tag=pato.registered] run tellraw @s [{"text": "[SISTEMA DE CUENTAS] ","color": "green"},{"text": "RECUERDE SU CONTRASEÑA","color": "red"}]
