#######
# Compiled from data/pt.evs/functions/login_system.mcscript
# to .//pt.evs/data/pt.evs/functions/login/login.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @a if entity @s[tag=pato.registered] unless score @s login matches 0 run scoreboard players operation @s pato.subtraction = @s login
execute as @a if entity @s[tag=pato.registered] unless score @s login matches 0 store result score @s pato.equals run scoreboard players operation @s pato.subtraction -= @s pato.password
execute as @a if entity @s[tag=pato.registered] unless score @s login matches 0 run scoreboard players reset @s pato.subtraction
execute as @a if entity @s[tag=pato.registered] unless score @s login matches 0 if score @s pato.equals matches 0 run function pt.evs:login/unlock_session
execute as @a if entity @s[tag=pato.registered] unless score @s login matches 0 unless score @s pato.equals matches 0 run tellraw @s [{"text": "[SISTEMA DE CUENTAS] ","color": "green"},{"text": "CONTRASEÑA INCORRECTA, ACCESO DENEGADO","color": "dark_red"}]
execute as @a if entity @s[tag=pato.registered] unless score @s login matches 0 run scoreboard players reset @s login
