#######
# Compiled from data/pt.evs/functions/login_system.mcscript
# to .//pt.evs/data/pt.evs/functions/login/register.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @a if entity @s[tag=!pato.registered] unless score @s register matches 0 store result score @s pato.password run scoreboard players operation @s pato.password = @s register
execute as @a if entity @s[tag=!pato.registered] unless score @s register matches 0 run tellraw @s [{"text": "[SISTEMA DE CUENTAS] ","color": "green"},{"text": "Recuerda tu contraseña: ","color": "yellow"},{"score": {"name": "@s", "objective": "pato.password"},"color": "gold"}]
execute as @a if entity @s[tag=!pato.registered] unless score @s register matches 0 run tag @s add pato.registered
execute as @a if entity @s[tag=!pato.registered] unless score @s register matches 0 as @s run function pt.evs:login/checker_message
execute as @a if entity @s[tag=!pato.registered] unless score @s register matches 0 run scoreboard players reset @s register
