#######
# Compiled from data/pt.evs/functions/login_system.mcscript
# to .//pt.evs/data/pt.evs/functions/login/trigger_enable.mcfunction
#
# Generated by Minecraft Script for 1.16
######
execute as @a if entity @s[tag=pato.registered] if entity @s[tag=pato.onLoginResponse] run scoreboard players enable @s login
execute as @a if entity @s[tag=pato.registered] if entity @s[tag=pato.onLoginResponse] run function pt.evs:login/login
execute as @a if entity @s[tag=pato.registered] unless entity @s[tag=pato.onLoginResponse] run scoreboard players enable @s changepass
execute as @a if entity @s[tag=pato.registered] unless entity @s[tag=pato.onLoginResponse] run function pt.evs:login/changepass
execute as @a unless entity @s[tag=pato.registered] run scoreboard players enable @s register
execute as @a unless entity @s[tag=pato.registered] run function pt.evs:login/register